# Generated by Django 4.2.7 on 2023-11-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="servicios", table="servicios",),
    ]
