# Generated by Django 4.2.7 on 2023-11-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_servicios_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaluos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coloniaid", models.IntegerField(max_length=100)),
                ("calle", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("edad", models.IntegerField()),
                ("dcreate", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "jos_av_avaluos", "managed": False,},
        ),
    ]
