# Generated by Django 4.2.7 on 2023-11-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clientes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tipos",
            fields=[
                ("tipoid", models.IntegerField(primary_key=True, serialize=False)),
                ("display", models.CharField(max_length=10)),
                ("descripcion", models.CharField(max_length=250)),
                ("consecutivo", models.IntegerField()),
            ],
            options={"db_table": "jos_av_tipos", "managed": False,},
        ),
        migrations.CreateModel(
            name="Valuadores",
            fields=[
                ("estatusid", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=250)),
            ],
            options={"db_table": "jos_av_estatus", "managed": False,},
        ),
    ]
