# Generated by Django 4.2.7 on 2023-11-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tipos_valuadores"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estatus",
            fields=[
                ("estatusid", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=250)),
            ],
            options={"db_table": "jos_av_estatus", "managed": False,},
        ),
        migrations.AlterModelTable(name="valuadores", table="jos_av_valuadores",),
    ]
