# Generated by Django 4.2.7 on 2023-11-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estados",
            fields=[
                ("estadoid", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=250)),
                ("clave", models.CharField(max_length=10)),
            ],
            options={"db_table": "jos_estados", "managed": False,},
        ),
        migrations.DeleteModel(name="Estado",),
    ]
