# Generated by Django 4.2.7 on 2023-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_estados_delete_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipios",
            fields=[
                ("municipioid", models.IntegerField(primary_key=True, serialize=False)),
                ("estadoid", models.IntegerField()),
                ("nombre", models.CharField(max_length=250)),
            ],
            options={"db_table": "jos_municipios", "managed": False,},
        ),
    ]
